### ISSUE TITLE
rvm and ruby 2.0 error

### ISSUE THREAD

**Issue by error400** [maltize/sublime-text-2-ruby-tests#161]
If i want to execute a test i get the following error:

``` bash
~/.rvm/rubies/ruby-2.0.0-p0/bin/ruby:1: invalid multibyte char (UTF-8)
[Finished in 0.2s with exit code 1]
```

any Suggestions?

**Comment by hnguyen94** [comment]
@jackchang but I have a problem if I use bundle it says:
bundler: command not found: -Itest
Install missing gem executables with `bundle install`

Any solutions?
