### ISSUE TITLE
Run commands from ruby project root

### ISSUE THREAD

**Issue by alex88** [maltize/sublime-text-2-ruby-tests#226]
Is there a way to run commands from the rails root?

It's because in sublime I open my `code` folder with all my projects in it, each project has a different ruby version, so in this case I'm in `code/projectname/spec/controller/users_controller_spec.rb` but running the specs from that file I get:

```
rbenv: rspec: command not found

The `rspec' command exists in these Ruby versions:
  jruby-1.7.9
  rbx-2.2.3
```

but my .ruby-version file states rbx-2.2.3 so the command isn't run within the project root folder.

Is there a way to solve this?

**Comment by newmen** [comment]
I suggest #251 pull request for fix it
