### ISSUE TITLE
How to run remotely?

### ISSUE THREAD

**Issue by Funfun** [maltize/sublime-text-2-ruby-tests#230]
my situation:

i'm developing on local machine and code stored also on that machine but application env (db, ruby, servers) locate within another machine (in same network) and required to invoke all actions within that machine.

So, question, is possible to configure plugin for run command like `single test run` remotely?

Many thanks

**Comment by EugZol** [comment]
There is such plugin for running PHP Unit tests: https://github.com/paza/RemotePHPUnit-for-Sublime-Text

It seems it works only on *nix host systems (it uses 'ssh' shell command). If your local machine is running OS X or Linux, you can try and adopt that plugin for Ruby tests.
