### ISSUE TITLE
Docker and fig support

### ISSUE THREAD

**Issue by zedtux** [maltize/sublime-text-2-ruby-tests#237]
Hello,

I'm trying to build an isolated environment thanks to Docker and Fig.
When I want to execute the tests of my project (Cucumber and RSpec), I'm using `fig run` which is working as expected (tests are executed and result is normally visible).

Then I have updated the configuration of sublime-text-2-ruby-tests in order to execute tests with `fig run web bundle exec` before `cucumber`, so the complete config is the following:

```
...
"run_cucumber_command": "/usr/local/bin/fig run web bundle exec cucumber ./{relative_path}",
"run_single_cucumber_command": "/usr/local/bin/fig run web bundle exec cucumber ./{relative_path} -l{line_number}",
...
```

The console is appearing but I can only see `[Finished in 10.5s]`.

I have a repository where it can be tested: https://github.com/zedtux/brewformulas.org.

Let me know if I can help.

**Comment by zedtux** [comment]
With the new fig there is no more output and the script I did in the past that was partially fixing the issue described in the issue docker/fig#462 is no more working.

The issue seems to be a buffering issue.

**Comment by zedtux** [comment]
Could this be a solution ?

http://stackoverflow.com/questions/230751/how-to-flush-output-of-python-print

**Comment by evgenyneu** [comment]
+1

**Comment by zedtux** [comment]
Apparently, repo no more maintained or not caring for the issues ... closing the issue.
