### ISSUE TITLE
Keybindings override defaults from ST3

### ISSUE THREAD

**Issue by ineu** [maltize/sublime-text-2-ruby-tests#238]
In Linux version of ST3 command to run all tests is bound to ctrl+shift+t. This keybinding is default in ST3 for `reopen_last_file` and is consistent with other applications like web browser. Plugins should not redefine such keybinding. Instead of these keys defaults could use ctrl+b, just like 'rspec' plugin does for build.
Thanks.

**Comment by jamonholmgren** [comment]
@daymun Thanks!
