### ISSUE TITLE
ctrl+shift+t conflicts with Sublime default setting 'reopen_last_file'

### ISSUE THREAD

**Issue by ethanyoung** [maltize/sublime-text-2-ruby-tests#249]
If a user is opening a spec file, then the key combination works fine -- it just runs the test. 

However, if the user is opening a non-spec file and he wants to reopen the last closed file, nothing happens and no prompt... 

This makes the user confused, since he might do not realise he is actuall triggering RubyTest plugin and think something wrong happens in Sublime default settings.

**Comment by jamonholmgren** [comment]
Duplicate of #247.

**Comment by ethanyoung** [comment]
I mapped it to another key, anyway.
