### ISSUE TITLE
ImageMagick is not visible when run RubyTest

### ISSUE THREAD

**Issue by ka8725** [maltize/sublime-text-2-ruby-tests#253]
In my Ruby code I use minimagick (it runs `mogrify` command in some cases). But when I run tests via RubyTests it says that there is no installed `mogrify` program in the system. But it's not true:

```shell
which mogrify
/usr/local/bin/mogrify
```

Any ideas why programs which are in the `/usr/local/bin` folder are not visible when I run RubyTest? May be is there an option to make it work?

**Comment by andypike** [comment]
I had a similar problem, and using the following fixed it for me so worth a try:

https://github.com/int3h/SublimeFixMacPath

Hope that helps

Andy

**Comment by ka8725** [comment]
Thanks, Andy. It works!
