### ISSUE TITLE
Color in test output using latest Sublime Text 2 build

### ISSUE THREAD

**Issue by mhartl** [maltize/sublime-text-2-ruby-tests#33]
These Sublime Text Ruby test functions are great, and I'm hoping to use them in the next edition of the [Ruby on Rails Tutorial screencasts](http://railstutorial.org/screencasts). Unfortunately, it looks like color test output might have been broken by the latest Sublime Text 2 beta (build 2165). Ever since upgrading, when I run the tests inside of Sublime Text the output console still appears, but the colors for passing/failing tests are gone. You can see what I mean in [this screenshot](http://dl.dropbox.com/u/375937/sublime_text_ruby_test_issue.png). Any help getting this fixed before I start recording the next edition of the screencasts (in the next couple of weeks) would be greatly appreciated.

**Comment by csalvato** [comment]
This is still not working for me.  Tried all the suggestions above but nothing seems to be working.

With Minitest Reporters On:
![screen shot 2015-01-18 at 7 42 01 pm](https://cloud.githubusercontent.com/assets/1158152/5794753/17ffbebe-9f4a-11e4-88ad-c09f486bc3ed.png)
![screen shot 2015-01-18 at 7 41 21 pm](https://cloud.githubusercontent.com/assets/1158152/5794755/1f979660-9f4a-11e4-96a6-0879ec9a0500.png)

With Minitest Reporters Off:
![screen shot 2015-01-18 at 7 42 45 pm](https://cloud.githubusercontent.com/assets/1158152/5794757/30be424a-9f4a-11e4-9f22-170b658faaa6.png)
![screen shot 2015-01-18 at 7 43 07 pm](https://cloud.githubusercontent.com/assets/1158152/5794761/412d32da-9f4a-11e4-896e-27a06e9176f3.png)

Using Sublime Text 2 Build 2221 and Rails 4.2.0.

**Comment by jamesfwz** [comment]
Hi, any solution?

**Comment by arefaslani** [comment]
use this package: https://github.com/aziz/SublimeANSI

**Comment by lrkaussie** [comment]
javiercr's solution works fine to me! Just change the color option on cucumber.yml to "no-color"

Thanks a lot. :+1:
