### ISSUE TITLE
Rspec not found

### ISSUE THREAD

**Issue by ghost** [maltize/sublime-text-2-ruby-tests#36]
I'm not sure this is necessarily an issue with the package, but hopefully you can help.

When i run a single rspec test, i get this output:

/bin/sh: rspec: command not found

In the console, i copy and paste the command that as created:

cd '/Users/user/Dropbox/code/app/' && rspec spec/controllers/profile_controller_spec.rb -l 163

When I run that command in Terminal, it works fine. Any why it wouldn't work from Sublime?

**Comment by newmen** [comment]
I fixed it in #250
