### ISSUE TITLE
How to make it work for rails test

### ISSUE THREAD

**Issue by vanakenm** [maltize/sublime-text-2-ruby-tests#46]
Hello, thanks for the plugin. Small question, one of your example [https://github.com/maltize/sublime-text-2-ruby-tests] show a Test class inheriting from Rails (ActionController::TestCase), but I cannot make any of those work (if I understand, the plugin launch the test using standard ruby test command, that fail to load some required parts of rails). Each time I try to run a test from a rails application it fails (message such as : " `require': no such file to load")

It is any way to make the plugin work with "rails" tests ?

Thanks !

**Comment by Aleksandaar** [comment]
No need to hack, just adjust the settings `"check_for_rvm": true, "check_for_bundler": true,' 
http://stackoverflow.com/a/14504365/1612469
