### ISSUE TITLE
"No test name!" when running single test with a name containing punctuation (with test/unit)

### ISSUE THREAD

**Issue by Sephi-Chan** [maltize/sublime-text-2-ruby-tests#83]
Hi,

I issue errors when I run a single test with a name containing punctuation (dot, comma, bang, …).
An alert box sayings "No test name!" pops.

``` Ruby
require 'test_helper'

class UserSignsInTest < ActionDispatch::IntegrationTest
  test "The user signs in with correct credentials." do
    anything
  end
end
```

For now I just avoid them. ;)

**Comment by lserman** [comment]
Just ran into the # problem as well, I think it's pretty common practice to use the # as a notation for instance methods, so you might have something like

```ruby
describe Message do
  describe '#sent?' do
    it 'is true when message has been sent' do
    end
  end
end
```

Something like this will cause the No test name error.
